#!/bin/bash

echo ""
echo "[VL]: E..."

# go to the shell file's dir
SHELL_DIR=$(dirname $BASH_SOURCE)
echo "** SHELL_DIR=[${SHELL_DIR}]"
source $SHELL_DIR/__ginger_utils.sh

# check params
if [ $# -eq 0 ]; then
    echo "Usage: "
    echo "$0 module_name"
    exit -1
fi
MODULE_NAME=$(get_module_name $1)
echo "[VL]: get module name: ${MODULE_NAME}"

PROC_NAME=$(get_module_proc_name ${MODULE_NAME})
echo "[VL]: get process name: ${PROC_NAME}"

# waiting module process running
echo
INTERVAL=5 # unit by seconds
MAX_COUNT=20
COUNT=0
while [ $COUNT -lt $MAX_COUNT ]; do
    MODULE_PID=$(ps -efw | grep ${PROC_NAME} | grep -v grep | awk '{print $2}')
    if [ "$MODULE_PID" = "" ]; then
        let COUNT++
        echo "[VL]: sleep ${INTERVAL}s to wait ${COUNT}/${MAX_COUNT}..."
        sleep ${INTERVAL}s
    else
        echo "[VL]: get ${PROC_NAME} pid: "
        echo "$MODULE_PID"
        break
    fi
done
if [ "$MODULE_PID" = "" ]; then
    echo "[VL]: wait ${MODULE_NAME} process ${PROC_NAME} failed."
    echo
    exit -10
fi

# waiting for log file generated by module process
echo
LOG_INTERVAL=3 # unit by seconds
LOG_MAX_COUNT=10
LOG_COUNT=0
while [ $LOG_COUNT -lt $LOG_MAX_COUNT ]; do
    if [ -f /home/ginger/latest/${MODULE_NAME}.log* ]; then
        LOG_FILE=$(ls -t /home/ginger/latest/${MODULE_NAME}.log* | head -1)
        echo "[VL]: get log file: ${LOG_FILE}"
        break
    fi
    let LOG_COUNT++
    echo "[VL]: sleep ${LOG_INTERVAL}s to wait ${LOG_COUNT}/${LOG_MAX_COUNT}..."
    sleep ${LOG_INTERVAL}s
done
if [ "$LOG_FILE" = "" ]; then
    echo "[VL]: no log file of ${MODULE_NAME} found."
    echo
    exit -20
fi

echo "[VL]: view ${MODULE_NAME}'s log file: $LOG_FILE..."
tail -f ${LOG_FILE}
